# LoRA Transfer Pipeline Configuration

# 路径配置
paths:
  models_dir: '/root/autodl-tmp/models'
  train_script: '/root/PAW/train_lora/train_cs_lora_lightning.py'
  eval_script: '/root/PAW/eval/lightning_eval.py'
  transfer_script: '/root/PAW/lora_adapter/scripts/transfer_lora_x.py'
  runs_dir: '/root/PAW/train_lora/runs'
  transferred_lora_dir: '/root/autodl-tmp/transferred_lora'
  results_dir: '/root/PAW/results'

# 训练配置
training:
  default_batch_size: 4
  default_max_steps: 700
  default_lr: '1e-5'
  # 要运行的数据集列表 - 不需要的可以注释掉
  datasets:
    # - 'piqa'
    - 'arc-challenge'
    # - 'arc-easy'
    # - 'hellaswag'
    # - 'winogrande'

# 评估配置
evaluation:
  sample_ratio: 0.1
  default_batch_size: 8

# 迁移配置
transfer:
  similarity_threshold: 0.0001

# 结果配置
results:
  csv_file: 'experiment_results.csv'
  markdown_file: 'experiment_summary.md'

# 通用配置
general:
  timestamp: null
