# Quick Test Configuration for LoRA Transfer Pipeline
# 专为快速测试设计，使用较少的训练步数和评估样本

# 路径配置 (与正常配置相同)
paths:
  models_dir: '../autodl-tmp/models'
  train_script: './train_lora/train_cs_lora_lightning.py'
  eval_script: './eval/lightning_eval.py'
  transfer_script: './lora_adapter/scripts/transfer_lora_x.py'
  runs_dir: './train_lora/runs'
  transferred_lora_dir: '../autodl-tmp/transferred_lora'
  results_dir: './results'

# 训练配置 (快速测试参数)
training:
  default_batch_size: 4
  default_max_steps: 40  # 减少训练步数
  default_lr: '1e-5'
  datasets:
    - 'arc-challenge'
    - 'arc-easy'
    - 'piqa'

# 评估配置 (快速测试参数)
evaluation:
  sample_ratio: 0.05  # 5%采样，更快评估
  default_batch_size: 8

# 迁移配置
transfer:
  similarity_threshold: 0.0001

# 结果配置
results:
  csv_file: 'experiment_results.csv'
  markdown_file: 'experiment_summary.md'

# 推荐的快速测试模型组合
recommended_models:
  source: 'Qwen-Qwen2.5-0.5B'
  target: 'Qwen_Qwen2.5-1.5B'
  dataset: 'arc-challenge'

# 实验管理配置
experiment_management:
  # 当发现已存在实验时的默认行为
  # 选项: 'prompt', 'continue', 'delete', 'abort'
  existing_experiment_action: 'prompt'
  
  # 删除现有输出时要清理的内容
  cleanup_targets:
    - 'training_outputs'    # 训练结果 (train_lora/runs/*)
    - 'transferred_lora'    # 迁移的LoRA (autodl-tmp/transferred_lora/*)
    - 'evaluation_results'  # 评估结果 (eval/results/*)
    - 'pipeline_results'    # Pipeline结果 (results/*)
  
  # 要保留的文件模式 (这些文件不会被删除)
  preserve_patterns:
    - '*.yaml'             # 配置文件
    - '*.py'               # Python脚本
    - 'README.*'           # 说明文档
    - '.git*'              # Git相关文件
