# 快速测试配置文件 - 专门用于0.5B→1.5B验证
# ===========================================

# 路径配置
paths:
  models_dir: "/root/autodl-tmp/models"
  results_dir: "/root/PAW/results"
  runs_dir: "/root/PAW/train_lora/runs"
  transferred_lora_dir: "/root/autodl-tmp/transferred_lora"
  eval_script: "/root/PAW/eval/lightning_eval.py"
  train_script: "/root/PAW/train_lora/train_cs_lora_lightning.py"
  transfer_script: "/root/PAW/lora_adapter/scripts/transfer_lora_x.py"

# 推荐的快速测试模型对
recommended_models:
  source: "Qwen-Qwen2.5-0.5B"    # 源模型：小而快
  target: "Qwen_Qwen2.5-1.5B"    # 目标模型：同系列更大
  dataset: "piqa"                 # 推荐数据集：简单快速（训练脚本会自动处理validation→test）

# 训练配置
training:
  default_batch_size: 4
  default_max_steps: 20          # 快速验证：20步足够
  default_lr: 1e-5
  datasets: 
    - "arc-challenge"
    - "arc-easy" 
    - "boolq"
    - "hellaswag"
    - "openbookqa"
    - "piqa"                     # 推荐用这个，比较简单
    - "winogrande"

# 评估配置  
evaluation:
  sample_ratio: 0.05             # 只用5%数据，快速验证
  
# 迁移配置
transfer:
  similarity_threshold: 0.0001

# 结果管理
results:
  csv_file: "experiment_results.csv"
  markdown_file: "experiment_summary.md"
  backup_results: true
