# LoRA迁移管道配置文件
# ===========================================

# 路径配置
paths:
  models_dir: "/root/autodl-tmp/models"
  results_dir: "/root/PAW/results"
  runs_dir: "/root/PAW/train_lora/runs"
  transferred_lora_dir: "/root/autodl-tmp/transferred_lora"
  eval_script: "/root/PAW/eval/lightning_eval.py"
  train_script: "/root/PAW/train_lora/train_cs_lora_lightning.py"
  transfer_script: "/root/PAW/lora_adapter/scripts/transfer_lora_x.py"

# 训练配置
training:
  default_batch_size: 4
  default_max_steps: 600
  default_lr: 1e-5
  datasets: 
    - "arc-challenge"
    - "arc-easy" 
    - "boolq"
    - "hellaswag"
    - "openbookqa"
    - "piqa"
    - "winogrande"

# 评估配置  
evaluation:
  sample_ratio: 1.0  # 使用100%测试集确保一致性
  
# 迁移配置
transfer:
  similarity_threshold: 0.0001

# 结果管理
results:
  csv_file: "experiment_results.csv"
  markdown_file: "experiment_summary.md"
  backup_results: true