# LoRA迁移管道配置文件
# ===========================================

# 路径配置
paths:
  models_dir: "/root/autodl-tmp/models"
  results_dir: "/root/PAW/results"
  runs_dir: "/root/PAW/train_lora/runs"
  transferred_lora_dir: "/root/autodl-tmp/transferred_lora"
  eval_script: "/root/PAW/eval/lightning_eval.py"
  train_script: "/root/PAW/train_lora/train_cs_lora_lightning.py"
  transfer_script: "/root/PAW/lora_adapter/scripts/transfer_lora_x.py"

# 训练配置
training:
  default_batch_size: 4
  default_max_steps: 600
  default_lr: 1e-5
  datasets: 
    - "arc-challenge"
    - "arc-easy" 
    - "boolq"
    - "hellaswag"
    - "openbookqa"
    - "piqa"
    - "winogrande"

# 评估配置  
evaluation:
  sample_ratio: 1.0  # 使用100%测试集确保一致性
  
# 迁移配置
transfer:
  similarity_threshold: 0.0001

# LoRA配置
lora:
  # LoRA基础参数
  r: 16                    # LoRA秩，控制适配器的复杂度
  lora_alpha: 32           # LoRA缩放参数，通常设为r的2倍
  lora_dropout: 0.1        # LoRA层的dropout率
  bias: "none"             # 偏置处理方式: "none", "all", "lora_only"
  
  # 目标层配置 - 决定对哪些层应用LoRA
  target_modules:
    # 保守配置 - 只对注意力机制的查询和值投影层进行LoRA
    - "q_proj"
    - "v_proj"
    
    # 标准配置 - 完整注意力层 (取消注释以启用)
    - "k_proj"
    - "o_proj"
    
    # 完整配置 - 包含FFN层 (取消注释以启用)
    - "gate_proj"
    - "up_proj" 
    - "down_proj"

# 结果管理
results:
  csv_file: "experiment_results.csv"
  markdown_file: "experiment_summary.md"
  backup_results: true
