# 现代化LoRA训练配置
model:
  name: "Qwen/Qwen2.5-0.5B"
  cache_dir: "./models"
  torch_dtype: "auto"
  device_map: "auto"
  trust_remote_code: true

lora:
  r: 8
  alpha: 16
  dropout: 0.05
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

training:
  output_dir: "./checkpoints/qwen2.5_lora"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 1
  learning_rate: 2.0e-4
  weight_decay: 0.01
  warmup_steps: 100
  logging_steps: 10
  eval_steps: 500
  save_steps: 1000
  save_total_limit: 2
  evaluation_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  dataloader_num_workers: 4
  remove_unused_columns: false
  report_to: "wandb"
  run_name: "qwen2.5_lora_training"
  fp16: true
  gradient_checkpointing: true
  
wandb:
  project: "qwen2.5-lora-training"
  entity: "your-wandb-entity"
  tags: ["lora", "qwen2.5", "fine-tuning"]
  
logging:
  level: "INFO"
  log_dir: "./logs"
  tensorboard_dir: "./tensorboard_logs"
